### ISSUE TITLE
동시성 문제 발생 유즈케이스 분석 및 대응

### ISSUE THREAD

**Issue by insightp25** [insightp25/hp12#23]
## TODO
- [x] 각 유즈케이스에 대한 동시성 문제 분석
- [x] DB 락, Redis 분산 락 등 다양한 해결방법 적용 케이스에 대해 비교
- [x]  분석 자료를 토대로 비즈니스 로직 개선 및 통합 테스트 작성
